# Configuration for get_data.py
job_type: Internship # Internship, Graduate, Temporary, Summer
headless: False
output_format: Excel # Excel, CSV, JSON


# Configuration for recom.py
user:
  job_interest: Software Engineer
  skills:  Marketing, Content Creation, Social Media
  industry: 'Art, Design, Culture'
top_k: 5